name = "BaseExtensions"
uuid = "10861165-1ac8-4f9f-8a8a-7c6e060a69e2"
authors = ["Jishnu Bhattacharya and contributors"]
version = "0.1.0"

[compat]
Aqua = "0.5"
Documenter = "0.26"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter", "Aqua"]
